apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: workflow-playground

resources:
  - resources/rbac/github.com-rolebinding.yaml
  - resources/rbac/read-only-rolebinding.yaml
  - resources/rbac/read-write-rolebinding.yaml
  - resources/rbac/submit-workflow-template-role.yaml
  - resources/rbac/workflow-role.yaml
  - resources/rbac/workflow-rolebinding.yaml
  - resources/rbac/workflow-sa.yaml
  - https://raw.githubusercontent.com/argoproj-labs/argo-workflows-catalog/master/templates/buildkit/manifests.yaml
  - https://raw.githubusercontent.com/argoproj-labs/argo-workflows-catalog/master/templates/slack/manifests.yaml
  - https://raw.githubusercontent.com/argoproj-labs/argo-workflows-catalog/master/templates/sendmail/manifests.yaml
  - https://raw.githubusercontent.com/argoproj-labs/argo-workflows-catalog/master/templates/distro/manifests.yaml
  - https://raw.githubusercontent.com/argoproj/argo-workflows/master/examples/artifacts-workflowtemplate.yaml
  - https://raw.githubusercontent.com/argoproj/argo-workflows/master/examples/ci-workflowtemplate.yaml
  - resources/workflows/artifacts-cronworkflow.yaml
  - resources/workflows/ci-cronworkflow.yaml
  - resources/workflows/coinflip-cronworkflow.yaml
  - resources/workflows/coinflip-workflowtemplate.yaml
  - resources/workflows/event-consumer-workfloweventbinding.yaml
  - resources/workflows/github-event-workflowtemplate.yaml
