apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/argoproj/argo-workflows/manifests/namespace-install
  - https://github.com/argoproj/argo-workflows/manifests/quick-start/base/minio
  - https://raw.githubusercontent.com/argoproj/argo-workflows/master/manifests/quick-start/base/artifact-repositories-configmap.yaml
  - resources/argo-ns.yaml
  - resources/argo-rolebinding.yaml
  - resources/argo-server-ingress.yaml
  - resources/argo-server-rolebinding.yaml
  - resources/argo-workflows-certificate.yaml
  - resources/argo-workflows-issuer.yaml
  - resources/workflow-count-resourcequota.yaml
  - resources/rbac/github.com-sa-secret.yaml
  - resources/rbac/github.com-sa.yaml
  - resources/rbac/read-only-clusterrole.yaml
  - resources/rbac/read-only-clusterrolebinding.yaml
  - resources/rbac/read-only-namespaced-clusterrole.yaml
  - resources/rbac/read-write-namespaced-clusterrole.yaml
  - resources/rbac/read-write-sa-secret.yaml
  - resources/rbac/read-write-sa.yaml
  - resources/rbac/user-default-login-sa-secret.yaml
  - resources/rbac/user-default-login-sa.yaml
  - resources/rbac/workflow-sa-secret.yaml
  - resources/rbac/workflow-sa.yaml

patches:
  - path: overlays/argo-server-deploy.yaml
  - path: overlays/argo-server-sa.yaml
  - path: overlays/workflow-controller-configmap.yaml
  - path: overlays/workflow-controller-deploy.yaml
  - path: overlays/argo-role.yaml
    options:
      allowKindChange: true
      allowNameChange: true
    target:
      group: rbac.authorization.k8s.io
      kind: Role
      name: argo-role
  - path: overlays/argo-rolebinding.yaml
    target:
      group: rbac.authorization.k8s.io
      kind: RoleBinding
      name: argo-binding
  - path: overlays/argo-server-role.yaml
    options:
      allowKindChange: true
      allowNameChange: true
    target:
      group: rbac.authorization.k8s.io
      kind: Role
      name: argo-server-role
  - path: overlays/argo-server-rolebinding.yaml
    target:
      group: rbac.authorization.k8s.io
      kind: RoleBinding
      name: argo-server-binding
