apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/keikoproj/governor/master/examples/pod-reaper.yaml

images:
  - name: governor
    newName: keikoproj/governor
    newTag: v0.4.1

patches:
  - path: overlays/pod-reaper-cr.yaml
  - path: overlays/pod-reaper-job-patch.yaml
    target:
      group: batch
      kind: CronJob
      name: pod-reaper
  - path: overlays/patch-priority-class.yaml
    target:
      group: batch
      kind: CronJob
