apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dex
  annotations:
    ingress.kubernetes.io/proxy-body-size: 100M
    ingress.kubernetes.io/app-root: "/"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - dex.apps.argoproj.io
    secretName: dex-secret
  rules:
  - host: dex.apps.argoproj.io
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: dex
            port:
              number: 5556